import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <html lang="en">
      <ClerkProvider>
        <body className="min-h-screen flex flex-row bg-[var(--tm-bg-main)] text-[var(--tm-text-main)] font-inter">
          <aside className="tm-glass w-[280px] min-h-screen flex flex-col items-center py-8 px-4 border-r border-[var(--tm-border)] shadow-lg">
            <div className="flex flex-col items-center mb-8">
              <span className="text-2xl font-bold tracking-widest text-[var(--tm-accent-blue)] tm-heading" style={{fontFamily: 'Sora, Inter, sans-serif'}}>TRACKME</span>
              <span className="text-xs text-[var(--tm-text-secondary)] mt-1">Live Intelligence Dashboard</span>
            </div>
            <nav className="flex flex-col gap-4 w-full">
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Dashboard</a>
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Devices</a>
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Map</a>
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Settings</a>
            </nav>
            <div className="mt-auto pt-8 text-xs text-[var(--tm-text-secondary)] opacity-70">© 2026 Trackme</div>
          </aside>
          <main className="flex-1 min-h-screen flex flex-col items-center justify-start bg-[var(--tm-bg-secondary)] px-0 sm:px-8 py-8 overflow-x-hidden">
            {children}
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
import { ClerkProvider } from '@clerk/nextjs';
import { useState } from 'react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="min-h-screen flex flex-row bg-[var(--tm-bg-main)] text-[var(--tm-text-main)] font-inter">
          {/* Mobile menu button */}
          <button
            className="fixed top-4 left-4 z-50 md:hidden tm-btn-ghost px-3 py-2 border border-[var(--tm-border)] bg-[var(--tm-bg-sidebar)] rounded-lg shadow"
            onClick={() => setSidebarOpen((v) => !v)}
            aria-label="Open sidebar"
          >
            <span className="text-xl">☰</span>
          </button>
          <aside className={`tm-glass w-[80vw] max-w-[280px] min-h-screen flex flex-col items-center py-8 px-4 border-r border-[var(--tm-border)] shadow-lg fixed md:static top-0 left-0 z-40 transition-transform duration-300 ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} md:translate-x-0 md:w-[280px] md:block bg-[var(--tm-bg-sidebar)]`}>
            <div className="flex flex-col items-center mb-8">
              <span className="text-2xl font-bold tracking-widest text-[var(--tm-accent-blue)] tm-heading" style={{fontFamily: 'Sora, Inter, sans-serif'}}>TRACKME</span>
              <span className="text-xs text-[var(--tm-text-secondary)] mt-1">Live Intelligence Dashboard</span>
            </div>
            <nav className="flex flex-col gap-4 w-full">
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Dashboard</a>
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Devices</a>
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Map</a>
              <a href="#" className="tm-btn-ghost px-4 py-2 text-left hover:bg-[rgba(59,130,246,0.08)] border-l-4 border-transparent hover:border-[var(--tm-accent-blue)] transition-all">Settings</a>
            </nav>
            <div className="mt-auto pt-8 text-xs text-[var(--tm-text-secondary)] opacity-70">© 2026 Trackme</div>
          </aside>
          <main className="flex-1 min-h-screen flex flex-col items-center justify-start bg-[var(--tm-bg-secondary)] px-0 sm:px-8 py-8 overflow-x-hidden md:ml-[280px]">
            {children}
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
